// Generated Firebase options for Femi-Friendly
// Based on: android/app/google-services.json
// Project: femi-friendly-app-7dcd4
// DO NOT edit this file manually — regenerate with FlutterFire CLI when keys change.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // iOS: add GoogleService-Info.plist and update below when available
        return android; // fallback until iOS config is added
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Android configuration — sourced from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuUMenn14M99Z_x-dDNC8W5H6J280SrUg',
    appId: '1:1063513374724:android:adb4d41cb1494176eeb551',
    messagingSenderId: '1063513374724',
    projectId: 'femi-friendly-app-7dcd4',
    storageBucket: 'femi-friendly-app-7dcd4.firebasestorage.app',
  );

  /// Web configuration — uses VAPID key for push
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuUMenn14M99Z_x-dDNC8W5H6J280SrUg',
    appId: '1:1063513374724:android:adb4d41cb1494176eeb551',
    messagingSenderId: '1063513374724',
    projectId: 'femi-friendly-app-7dcd4',
    storageBucket: 'femi-friendly-app-7dcd4.firebasestorage.app',
  );
}
